version: '2'

services:
  telegram_bot:
      build:
          context: .
          dockerfile: ./bot.Telegram.Dockerfile
      stdin_open: true
      tty: true
      environment:
        - MAX_TYPING_TIME=8
        - MIN_TYPING_TIME=1
        - WORDS_PER_SECOND_TYPING=10
        - TRAINING_EPOCHS=15
        - TELEGRAM_ACCESS_TOKEN=${TELEGRAM_ACCESS_TOKEN}
        - VERIFY=${VERIFY}
        - WEBHOOK_URL= ${WEBHOOK_URL}/webhooks/telegram/webhook

        # Should be set to 'production' or 'beta' or 'dev'
        - ENVIRONMENT_NAME=localhost
        # Last commit hash using this command: git rev-parse HEAD
        - BOT_VERSION=0.1.0-alpha
      ports:
        - 5001:5001
      # depends_on:
      #   - actions
      volumes:
        - ./bot:/bot

  # actions:
  #   build:
  #       context: .
  #       dockerfile: ./actions.Dockerfile
  #   ports:
  #     - 5055:5055
  #   volumes:
  #     - ./bot/actions:/bot/actions
  #     - ./bot/Makefile:/bot/Makefile
  #   command: "make run-actions"
